### ISSUE TITLE
Update Elasticsearch version

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid#300]
We're on the oldest version of Elasticsearch that is still supported (1.3.x). It's high time to start work on updating our servers. I suggest we use this as an umbrella ticket for incremental updates of individual lobid services:
- [x] Update hbz01 Elasticsearch version: https://github.com/hbz/mabxml-elasticsearch/issues/25
- [x] Update lobid-organisations Elasticsearch version: https://github.com/hbz/lobid-organisations/issues/130
- [x] Update lobid-resources Elasticsearch version: https://github.com/hbz/lobid-resources/issues/70

This covers the 2.0 services. For the 1.x API, we could consider fading them out on the current version.
